
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: Rediffmail@1409
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9000